### PR TITLE
chore: Move the Jekyll docs in the sub folder

### PR DESCRIPTION
**Pull request by tisonkun**
[INFRA-25486](https://issues.apache.org/jira/browse/INFRA-25486)

cc @sebbASF @martin-g 

I'll commit the docusaurus code in `docusaurus` subdir later. Please check if this is the direction you agree to go on.

### CODE REVIEW

**Review by sebbASF — CHANGES_REQUESTED** [review]
-1.
It's not possible to checkout a subdirectory from Git, so users will have to check out all the possible templates (there may be more in future) and then select the correct one.
This is extra work, and not scalable

**Comment by tisonkun** [comment]
@sebbASF What I disagree with is maintaining the docusaurus branch in a hidden branch and keeping the unmaintained Jekyll branch as the default. If you have other suggestions, we can discuss them. As long as the maintained branch is more visible, it's reasonable to keep improving.

**Comment by martin-g** [comment]
@tisonkun Yet another option is to create a new repo, e.g. `apache-website-template-docusaurus`!
It will be much simpler to maintain than this one!

**Comment by tisonkun** [comment]
@martin-g sounds reasonable :D. And it seems that we need infra's help for doing so. (Self-serve repo creation must associated with a PMC and with name $projectName-xxx)

I'm OK with your suggestion here. And since sebb is in the context, I'd like to wait a bit for their opinion before opening an INFRA ticket.

**Comment by sebbASF** [comment]
I agree with martin-g.
The new template is not an upgrade, it is an incompatible alternative.
Could perhaps be compared to changing from Java to Kotlin.

**Comment by tisonkun** [comment]
Thanks for your suggestion! I'll create a new ticket for creating the repo. The name is to be determinated. Let's continue on the ticket with INFRA.

**Pull request closed without merging**
